{% set version="0.5.0" %}
{% set name="ichorCNA" %}
{% set org="GavinHaLab" %}


package:
  name: 'r-{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/{{ org|lower }}/{{ name|lower }}/archive/refs/tags/v{{ version }}.zip
  sha256: c046af1978bd38b42b9fc71febfb20ff2657795ab0548ed2c60fe97244f3f207

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - perl  # for adding in correct path references to scripts
    - 'bioconductor-genomeinfodb >=1.26.7'
    - 'bioconductor-hmmcopy >=1.32.0'
    - 'bioconductor-genomicranges >=1.42.0'
    - r-optparse
    - r-plyr
  run:
    - r-base
    - 'bioconductor-genomeinfodb >=1.26.7'
    - 'bioconductor-hmmcopy >=1.32.0'
    - 'bioconductor-genomicranges >=1.42.0'
    - r-optparse
    - r-plyr

test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
    - runIchorCNA.R -h 2>&1 | grep Usage
    - createPanelOfNormals.R -h 2>&1 | grep Usage

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: GPL-3.0-only
  license_file: LICENSE
  summary:  Estimating tumor fraction in cell-free DNA from ultra-low-pass whole genome sequencing.
