{% set version = "0.8.0" %}
{% set sha256 = "c0d08bbf3059296e4819d33c6ff9282cfdd4d97087213c2d9aa0b5943ced60f4" %}

package:
  name: tower-cli
  version: {{ version }}

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/seqeralabs/tower-cli/releases/download/v{{ version }}/tw-linux-x86_64
  sha256: {{ sha256 }}

requirements:
  host:
    - openjdk >=11,<=20
  run:
    - openjdk >=11,<=20

test:
  commands:
    - tw --help
    - tw info

about:
  home: "https://github.com/seqeralabs/tower-cli"
  license: "MPL-2.0"
  summary: "The Tower CLI an interface to Nextflow Tower via the CLI"
